# Harvest configuration file

# Database settings
database:
  path: "db/images.db"

# Storage settings
storage:
  path: "storage"
  max_file_size: 10485760  # 10MB in bytes

# Download settings
download:
  timeout: 30
  max_concurrent: 5
  retry_attempts: 3

# Deduplication settings
deduplication:
  enabled: true
  threshold: 5  # Perceptual hash threshold
  keep_strategy: "first"  # first, smallest, largest

# API settings
apis:
  unsplash:
    access_key: ""  # Add your Unsplash access key here
    rate_limit: 50  # requests per hour

# Logging settings
logging:
  level: "INFO"
  file: "logs/harvest.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Scheduler settings (for automated harvesting)
scheduler:
  enabled: false
  jobs:
    - name: "daily_harvest"
      schedule: "0 9 * * *"  # Daily at 9 AM
      source: "unsplash"
      query: "nature"
      count: 10

# Proxy settings
proxy:
  enabled: false
  rotation_strategy: "round_robin"  # round_robin, random, weighted
  health_check_interval: 300  # 5 minutes
  max_failures: 3
  health_check_timeout: 10
  proxies:
    # Example proxy configurations (replace with your actual proxies)
    # - host: "proxy1.example.com"
    #   port: 8080
    #   username: "user1"
    #   password: "pass1"
    #   protocol: "http"
    #   country: "US"
    #   provider: "provider1"
    # - host: "proxy2.example.com"
    #   port: 3128
    #   username: "user2"
    #   password: "pass2"
    #   protocol: "http"
    #   country: "UK"
    #   provider: "provider2"

# Backup settings
backup:
  storage_path: "storage"
  db_path: "db/images.db"
  backup_root: "backups"
  compression: true
  encryption: false
  encryption_key: null  # Set to enable encryption
  retention_days: 30
  max_backups: 10
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - "__pycache__"
    - "*.pyc"
    - ".DS_Store"